name: Build unstable images every new push to main

on:
  push:
    branches:
      - main

env:
  IMG_REGISTRY_HOST: quay.io
  IMG_REGISTRY_ORG: kuadrant
  IMG_NAME: testsuite
  IMG_TAGS: unstable ${{ github.sha }}

jobs:
  build-unstable:
    name: Build unstable images every new push to main
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # ratchet:actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # ratchet:docker/setup-qemu-action@v3

      - name: Build unstable and sha images
        id: build-image
        uses: redhat-actions/buildah-build@9dc2ade9b5db229966b5025ae266311e12f349c4 # ratchet:redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMG_NAME }}
          tags: ${{ env.IMG_TAGS }}
          layers: true
          platforms: linux/amd64,linux/arm64
          containerfiles: |
            ./Dockerfile

      - name: Push images to quay
        uses: redhat-actions/push-to-registry@5860fc963bf8f2b3221773a023141612f010c469 # ratchet:redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMG_REGISTRY_HOST }}/${{ env.IMG_REGISTRY_ORG }}
          username: ${{ secrets.IMG_REGISTRY_USERNAME }}
          password: ${{ secrets.IMG_REGISTRY_TOKEN }}

